services:
  - type: web
    name: dicastri-medusa-backend
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: cd medusa && npm install && npm run build
    startCommand: cd medusa && npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: MEDUSA_ADMIN_ONBOARDING_TYPE
        value: default
      - key: REDIS_URL
        value: redis://red-placeholder:6379
      - key: NODE_ENV
        value: production
      - key: STORE_CORS
        sync: false
      - key: ADMIN_CORS
        sync: false
      - key: AUTH_CORS
        sync: false
      - key: STRIPE_API_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
